clients:
  file: excel_files/clients.xlsx
  fields:
    - Client Name
    - Client ID
    - Type of Company
    - Location
    - Contact Person 1
    - Contact Person 2
    - Contact Person 3
    - Onboarding status
    - Area of Interest

opportunities:
  file: excel_files/opportunities.xlsx
  fields:
    - Client Name
    - Role
    - Opp ID
    - Date Received
    - JD
    - Job Location
    - Exp Bracket
    - Budget
    - Expected Notice Period
    - Priority
    - Special comments
    - Deal Status
    - Number of Candidates Shared
    - Name of Candidates Shared
    - Closed On

resumes:
  file: excel_files/resumes.xlsx
  fields:
    - Entry ID
    - Name
    - Source
    - Top Skills
    - Resume
    - Location
    - Current Organization
    - Screener Name
    - Screener Comments
    - First Interviewer Name
    - First interviewer Comments
    - Identified for Roles
    - Years of Experience
    - Current CTC

onedrive:
  client_id: cc5853e1-b525-46b9-af84-2b40061c1286
  client_secret: NT38Q~euJQaeYM4rzvOojkN2-sKpcBqKvYqWkaP~
  tenant_id: 5775e378-abf7-437d-8ea2-2ad81e4adda6
  user_email: tech.support@sunfinity.tech
  user_id: e72c0115-4900-4322-830f-37216cf0c9fd
